using CSV
using DataFrames
using Statistics
using Printf
using Dates

"""
    collect_d_eff_series(data_dir)

Collect D_eff values from trajectory CSVs in chronological filename order.
Skips empty files and rows with missing/non-finite D_eff values.
"""
function collect_d_eff_series(data_dir::AbstractString)
    files = sort(filter(f -> startswith(f, "trajectory_") && endswith(f, ".csv"), readdir(data_dir)))

    d_eff_all = Float64[]
    files_used = 0
    rows_used = 0

    for f in files
        path = joinpath(data_dir, f)
        if filesize(path) == 0
            @info "Skipping empty trajectory file" file=path
            continue
        end

        df = CSV.read(path, DataFrame)
        colnames = String.(names(df))
        if !("D_eff" in colnames)
            @warn "Skipping file with no D_eff column" file=path
            continue
        end

        if "TimeIdx" in colnames
            sort!(df, "TimeIdx")
        end

        vals = Float64[]
        for v in df[!, "D_eff"]
            if !ismissing(v)
                x = Float64(v)
                if isfinite(x)
                    push!(vals, x)
                end
            end
        end

        if !isempty(vals)
            append!(d_eff_all, vals)
            files_used += 1
            rows_used += length(vals)
        end
    end

    return d_eff_all, files_used, rows_used
end

"""
    regenerate_all_diagnostics(; data_dir="data", output_tex="drafts/sections/generated/diagnostics_generated.tex")

Recompute D_eff summary statistics from trajectory CSVs and export TeX macros.
"""
function regenerate_all_diagnostics(; data_dir="data", output_tex="drafts/sections/generated/diagnostics_generated.tex")
    D_eff_all, files_used, rows_used = collect_d_eff_series(data_dir)

    if isempty(D_eff_all)
        error("No usable D_eff samples found in trajectory CSV files under $(data_dir).")
    end

    split_idx = min(3024, length(D_eff_all))

    D_eff_mean = mean(D_eff_all)
    D_eff_early = mean(@view D_eff_all[1:split_idx])
    D_eff_late = split_idx < length(D_eff_all) ? mean(@view D_eff_all[(split_idx + 1):end]) : D_eff_early
    D_eff_min = minimum(D_eff_all)
    D_eff_max = maximum(D_eff_all)

    timestamp = Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SS")

    mkpath(dirname(output_tex))
    open(output_tex, "w") do f
        write(f, "% AUTO-GENERATED by regenerate_all_diagnostics()\n")
        write(f, "% DO NOT EDIT MANUALLY\n")
        write(f, "% Generated UTC: $(timestamp)\n")
        write(f, "% Source: trajectory CSVs in $(data_dir)\n")
        write(f, "% Samples: $(length(D_eff_all)); files used: $(files_used); rows used: $(rows_used)\n\n")

        @printf(f, "\\newcommand{\\DefEffMean}{%.2f}\n", D_eff_mean)
        @printf(f, "\\newcommand{\\DefEffEarly}{%.2f}\n", D_eff_early)
        @printf(f, "\\newcommand{\\DefEffLate}{%.2f}\n", D_eff_late)
        @printf(f, "\\newcommand{\\DefEffMin}{%.2f}\n", D_eff_min)
        @printf(f, "\\newcommand{\\DefEffMax}{%.2f}\n", D_eff_max)
    end

    println("✓ Wrote $(output_tex)")
    println("  Files used: $(files_used), rows used: $(rows_used)")
    println("  D_eff: mean=$(round(D_eff_mean, digits=2)), early=$(round(D_eff_early, digits=2)), late=$(round(D_eff_late, digits=2))")
    println("  Range: min=$(round(D_eff_min, digits=2)), max=$(round(D_eff_max, digits=2))")
    println("  Include in manuscript preamble (optional): \\input{sections/generated/diagnostics_generated.tex}")
end

regenerate_all_diagnostics()
