module TexExporter

using DataFrames
using Printf
using Dates
using LinearAlgebra

export export_parameters, export_table, export_macros

function is_math_mode_string(s::AbstractString)
    return startswith(s, "\$") && endswith(s, "\$")
end

function normalize_tex_notation(s::AbstractString)
    out = String(s)
    out = replace(out, "\\text{sech}" => "\\operatorname{sech}")
    out = replace(out, "\\text{diag}" => "\\operatorname{diag}")
    out = replace(out, "z_{\\mathrm{center}}" => "z_c")
    out = replace(out, "\\alpha_{\\mathrm{stretch}}" => "\\alpha_s")
    out = replace(out, "L_{\\mathrm{domain}}" => "L_d")
    out = replace(out, "\\epsilon_{\\text{mach}}" => "\\epsilon_{\\mathrm{mach}}")
    out = replace(out, "\\mathbf{A}_{\\mathrm{obs}}" => "\\mathbf{a}_{\\mathrm{obs}}")
    out = replace(out, "z_{\\mathrm{min}}" => "z_{\\min}")
    out = replace(out, "z_{\\mathrm{max}}" => "z_{\\max}")
    return out
end

function tex_escape(s::AbstractString)
    out = replace(s, "\\" => "\\textbackslash{}")
    out = replace(out, "_" => "\\_")
    out = replace(out, "%" => "\\%")
    out = replace(out, "&" => "\\&")
    out = replace(out, "#" => "\\#")
    out = replace(out, "{" => "\\{")
    out = replace(out, "}" => "\\}")
    return out
end

function format_cell(x; digits::Int=3)
    if ismissing(x)
        return "--"
    elseif x isa Integer
        return string(x)
    elseif x isa AbstractFloat
        if !isfinite(x)
            return "--"
        elseif abs(x) >= 1000 || (abs(x) > 0 && abs(x) < 1e-3)
            return @sprintf("%.2e", x)
        else
            return @sprintf("%.*f", digits, x)
        end
    elseif x isa Number
        return string(x)
    else
        s = normalize_tex_notation(string(x))
        return is_math_mode_string(s) ? s : tex_escape(s)
    end
end

function infer_align(df::DataFrame)
    n = ncol(df)
    if n <= 0
        return "l"
    end
    return "l" * repeat(" c", n - 1)
end

function export_macros(output_path::AbstractString,
        macros::AbstractDict{<:AbstractString,<:AbstractString};
        xspace_keys::AbstractVector{<:AbstractString}=String[])
    mkpath(dirname(output_path))
    keys_sorted = sort!(collect(keys(macros)))
    xspace_key_set = Set(String.(xspace_keys))

    open(output_path, "w") do io
        println(io, "% Auto-generated by scripts/TexExporter.jl. Do not edit manually.")
        println(io, "% Generated UTC: ", Dates.format(Dates.now(Dates.UTC), dateformat"yyyy-mm-ddTHH:MM:SS"))
        for k in keys_sorted
            v = macros[k]
            if k in xspace_key_set && !occursin("\\xspace", v)
                v *= "\\xspace"
            end
            # Use provide+renew so later generated files can override defaults safely.
            println(io, "\\providecommand{\\" * k * "}{" * v * "}")
            println(io, "\\renewcommand{\\" * k * "}{" * v * "}")
        end
    end
end

# 1. Export Hyperparameters as LaTeX Macros
function export_parameters(ws, output_path;
        tower_observation_levels::Int=8,
        spectral_order::Int=ws.N,
        svd_tolerance_floor::Float64=max(tower_observation_levels, ws.N + 1) * eps(Float64),
        energy_floor_threshold::Float64=1e-4)

    n_nodes = ws.N + 1
    z_min = minimum(ws.z_atm)
    z_max = maximum(ws.z_atm)
    alpha = ws.alpha_stretch
    dz_vals = abs.(diff(ws.z_atm))
    dz_min = isempty(dz_vals) ? NaN : minimum(dz_vals)
    dz_max = isempty(dz_vals) ? NaN : maximum(dz_vals)
    kappa_m = cond(ws.Manifold_Mass)

    macros = Dict{String,String}(
        "GridNodes" => string(n_nodes),
        "TowerMin" => @sprintf("%.2f\\,\\mathrm{m}", z_min),
        "TowerMax" => @sprintf("%.2f\\,\\mathrm{m}", z_max),
        "TowerMinMeters" => @sprintf("%.2f", z_min),
        "TowerMaxMeters" => @sprintf("%.2f", z_max),
        "StretchAlpha" => @sprintf("%.1f", alpha),
        "alphaStretchBaseline" => @sprintf("%.1f", alpha),
        "DzMinMeters" => @sprintf("%.3f", dz_min),
        "DzMaxMeters" => @sprintf("%.3f", dz_max),
        "KappaMassBaseline" => @sprintf("%.0f", kappa_m),
        "TowerObservationLevels" => string(tower_observation_levels),
        "SpectralOrder" => string(spectral_order),
        "SvdToleranceFloor" => @sprintf("%.2e", svd_tolerance_floor),
        "EnergyFloorThreshold" => @sprintf("%.1e", energy_floor_threshold),
        # Fallback diagnostics macros so manuscript compiles even before synoptic export runs.
        "ProfilesTotal" => "0",
        "ProfilesCampaignPool" => "0",
        "ProfilesStableWindow" => "0",
        "RankMedian" => "0.00",
        "RankStd" => "0.00",
        "RankCompression" => "0",
        "SilhouettePeak" => "0.000",
        "WindowSEarly" => "0.000",
        "WindowSTransitional" => "0.000",
        "WindowSIOP" => "0.000"
    )

    export_macros(output_path, macros; xspace_keys=["ProfilesTotal"])
end

# 2. Convert DataFrames directly into formatted LaTeX Booktabs Tables
function export_table(df::DataFrame, output_path; caption="", label="", align::Union{Nothing,String}=nothing, digits::Int=3)
    mkpath(dirname(output_path))
    colspec = isnothing(align) ? infer_align(df) : align

    open(output_path, "w") do io
        println(io, "% Auto-generated by scripts/TexExporter.jl. Do not edit manually.")
        println(io, "\\begin{table}[htbp]")
        println(io, "  \\centering")
        if !isempty(caption)
            # Preserve TeX math/control sequences in captions after normalization.
            cap_norm = normalize_tex_notation(caption)
            println(io, "  \\caption{" * cap_norm * "}")
        end
        if !isempty(label)
            label_norm = replace(string(label), "_" => "-", " " => "-")
            println(io, "  \\label{" * label_norm * "}")
        end
        println(io, "  \\begin{tabular}{" * colspec * "}")
        println(io, "    \\toprule")

        # Print headers
            headers = String[]
            for n in names(df)
                s = normalize_tex_notation(string(n))
                push!(headers, is_math_mode_string(s) ? s : tex_escape(s))
            end
        println(io, "    " * join(headers, " & ") * " \\\\")
        println(io, "    \\midrule")

        # Print data rows with strict rounding
        for row in eachrow(df)
            row_str = join([format_cell(row[c]; digits=digits) for c in names(df)], " & ")
            println(io, "    " * row_str * " \\\\")
        end

        println(io, "    \\bottomrule")
        println(io, "  \\end{tabular}")
        println(io, "\\end{table}")
    end
end

end # module